id_textbox_username = "email-id"
id_textbox_password = "password"
id_checkbox_remember = "remember"
link_logout="link:Sign Out"
link_login="link:Sign In"
name_btn_submit="submit-name"
id_SignIn="SignIn"
new_Customer="new-customer"
id_textbox_email="EmailAddress"
id_textbox_first_name="FirstName"
id_textbox_last_name="LastName"
id_City="City"
id_StateOrRegion="StateOrRegion"
xpath_Gender="//*[@id='loginform']/div/div/div/div/form/div[6]/input[2]"
xpath_btn_submit="//*[@id='loginform']/div/div/div/div/form/button"
xpath_table="xpath=//table[@id='customers']"
xpath_line_customer="xpath=//table[@id='customers']/tbody/tr"
link_cancel= "link:Cancel"
